# Generated by Django 5.2.1 on 2025-05-25 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAutoCompilationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=30)),
                ('value', models.CharField(blank=True, max_length=30)),
                ('unit', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDoseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('dose_amount', models.FloatField()),
                ('dose_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('default_dose_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_dose_unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('taken_time', models.TimeField(blank=True, null=True)),
                ('taken_status', models.CharField(choices=[('be_taken', 'Alınacak'), ('taken', 'Aldındı'), ('pass', 'Pas')], default='be_taken', max_length=10)),
                ('dose_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('dose_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.medicationdosetime')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('custom', 'Özel')], default='daily', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('doses_per_period', models.PositiveIntegerField(default=1)),
                ('dose_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication.medication')),
                ('days_of_week', models.ManyToManyField(blank=True, to='medication.weekday')),
            ],
        ),
        migrations.AddField(
            model_name='medicationdosetime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='medication.medicationschedule'),
        ),
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='medicationdosetime',
            unique_together={('schedule', 'time')},
        ),
        migrations.CreateModel(
            name='WeeklyDosePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('dose_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dose_unit', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('reminder_times', models.JSONField(default=list)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='medication.medicationschedule')),
            ],
            options={
                'unique_together': {('schedule', 'week_number')},
            },
        ),
    ]
