# Generated by Django 5.2.1 on 2025-05-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='taken_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
