# Generated by Django 5.2.1 on 2025-05-25 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdosetime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_times', to='medication.medicationschedule'),
        ),
        migrations.DeleteModel(
            name='WeeklyDosePlan',
        ),
    ]
