# Generated by Django 5.2.1 on 2025-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medicationlog_taken_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='taken_status',
            field=models.CharField(choices=[('be_taken', 'Alınacak'), ('taken', 'Aldındı'), ('pass', 'Pas')], default='be_taken', max_length=10),
        ),
    ]
