# Generated by Django 5.2.1 on 2025-05-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_medicationlog_taken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='dose_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.medicationdosetime'),
        ),
    ]
