# Generated by Django 5.2.1 on 2025-05-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_medicationlog_dose_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDosePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('dose_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dose_unit', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('reminder_times', models.JSONField(default=list)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='medication.medicationschedule')),
            ],
            options={
                'unique_together': {('schedule', 'week_number')},
            },
        ),
    ]
