[tool.poetry]
name = "django-development-templates"
version = "0.1.0"
description = ""
authors = ["F4ruk.seker <ahmetfaruk731@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.2"
django-cors-headers = "^4.7.0"
django-environ = "^0.12.0"
djangorestframework = "^3.16.0"
djangorestframework-simplejwt = "^5.5.0"
# psycopg2 = "^2.9.10"
psycopg2-binary = "^2.9.10"
tzdata = "^2025.2"
jupyter = "^1.1.1"
django-extensions = "^4.1"
notebook = "^7.4.2"
ipython = "^9.2.0"
jupyterlab = "^4.4.2"
django-allauth = "^65.8.0"
django-filter = "^25.1"
celery = "^5.5.2"
redis = "^6.2.0"
django-celery-beat = "^2.8.1"
pywebpush = "^2.0.3"
django-sslserver = "^0.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
