from .water_tracking_views import WaterEntryListCreateView, WaterEntryDeleteView, WaterGoalView
from .weight_entry_list_create_view import WeightEntryListCreateView
from .weight_entry_delete_view import WeightEntryDeleteView
