# Generated by Django 5.2.1 on 2025-05-11 19:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAutoCompilationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ilacın adı', max_length=255)),
                ('notes', models.CharField(blank=True, help_text='bu ilaç için bit not ekleyin (opsiyonel)', max_length=500)),
                ('hunger_situation', models.CharField(default='non', help_text='Açlık durumu (Fark etmez|aç|tok)', max_length=10)),
                ('start_date', models.DateField(blank=True, help_text='Varsa ilaca başlama Tarihi', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Varsa bitiş tarihi', null=True)),
                ('often', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='StageSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField(default=0.0, help_text='ilacın gramajı')),
                ('unit_type', models.CharField(max_length=10)),
                ('range_start_date', models.DateField()),
                ('range_end_date', models.DateField()),
                ('range_length', models.IntegerField(help_text='Aralık uzunlu')),
                ('range_type', models.CharField(help_text='Aralık tipi, (Gün|Hafta|Ay|Yıl)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationReminderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='medication_management.medicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationUseHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField()),
                ('use_time', models.TimeField()),
                ('dosage', models.FloatField(blank=True)),
                ('dosage_type', models.CharField(blank=True, max_length=30)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medication_management.medicationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='medicationmodel',
            name='stages',
            field=models.ManyToManyField(to='medication_management.stagesteps'),
        ),
    ]
