# Generated by Django 5.2.1 on 2025-05-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationusehistorymodel',
            name='use_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicationusehistorymodel',
            name='use_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
